// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk8LnFUA71pLeiKdEtkc2HhnXH163FYSw',
    appId: '1:669753193612:android:4a3c81abd49f49288fb7a9',
    messagingSenderId: '669753193612',
    projectId: 'fcm-1abb4',
    storageBucket: 'fcm-1abb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6d3A3CC0dFLDCqb8F4WRCBqFOfwN1sIM',
    appId: '1:669753193612:ios:22ad8c87396e56c38fb7a9',
    messagingSenderId: '669753193612',
    projectId: 'fcm-1abb4',
    storageBucket: 'fcm-1abb4.appspot.com',
    iosClientId: '669753193612-3oi8jd3uq47t8digpjhmci004b4ep164.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmtest',
  );
}
